theme: jekyll-theme-midnight

gem "github-pages", group: :jekyll_plugins


# description: What's the best strategy to win in PUBG? Should you sit in one spot and hide your way into victory, or do you need to be the top shot? Let's let the data do the talking!


show_downloads: true
